HealthInsurenceSystem/Models/Policy.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace HealthInsurenceSystem.Models
{
    public partial class Policy
    {
        [Key]
        [StringLength(50, ErrorMessage = "Add Policy")]
        public string Ptype { get; set; }
     
        public int? MinAge { get; set; }
        
        public int? MaxAge { get; set; }
        public int? MonthPremium { get; set; }
        public int? Duration { get; set; }
    }
}

HealthInsurenceSystem/Controllers/PoliciesController.cs
using HealthInsurenceSystem.Data;
using HealthInsurenceSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;

namespace HealthInsurenceSystem.Controllers
{
    public class PoliciesController : Controller
    {

        private readonly ApplicationDbContext _db;

        public PoliciesController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {

            IEnumerable<Policy> objList = _db.Policy;
            return View(objList);
        }
        public IActionResult Interest()
        {

            return View();
        }
        public IActionResult knowmore()
        {
            return View();
        }
        public IActionResult addtocart(string Ptype)
        {
            
            var obj = _db.Policy.Find(Ptype);
            return View(obj);
        }
        public IActionResult deletefromcart(string Ptype)
        {
            var obj = _db.Policy.Find(Ptype);
            return View(obj);
        }
        public IActionResult SuperPlatinum()
        {
            return View();
        }
        public IActionResult Standard()
        {
            return View();
        }
        public IActionResult Gold()
        {
            return View();
        }
        public IActionResult Platinum()
        {
            return View();
        
        }
        public IActionResult Silver()
        {
            return View();
        }

        public IActionResult payonline()
        {
        
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult addtocart(Interested obj)
        {

            if (ModelState.IsValid)
            {
                _db.Interested.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Interest");
            }
            return View(obj);
        }
    }
}

HealthInsurenceSystem/Controllers/PolicyController.cs
using HealthInsurenceSystem.Data;
using HealthInsurenceSystem.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HealthInsurenceSystem.Controllers
{
    public class PolicyController : Controller
    {
        private readonly ApplicationDbContext _db;

        public PolicyController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            String email = HttpContext.Session.GetString("emailID"); 
            IEnumerable<Customer> x1 = _db.Customer.Where(a => a.Cemail == email);
            
            return View(x1);
        }
    }
}

HealthInsurenceSystem/Views/Policies/Gold.cshtml
@{
    ViewData["Title"] = "knowmore";
}

<h1>More About Health Insurance Plans</h1>
<img src="https://www.what-a-blog.com/wp-content/uploads/2020/05/aa-Cover-0mfd5vvu77f1bvrtjhg0fc7t54-20200330160440.Medi_.jpeg" />
<img src="https://www.policybazaar.com/images/Health/what-is-health-insurance.png" />

<hr />

<h3><u>Gold Plan</u></h3>
<h5>Direct Claim Settlement </h5>
<p>No third party agents involved. Get your claims processed painlessly by our customer service team directly. </p>

<h5> All Day Care Treatments </h5>
<p>Your health insurance will cover host of day care procedures. </p>
<h5>  Pre & Post Hospitalisation </h5>
<p>We cover expenses 30 days before hospitalisation and 60 days post-discharge.</p>
<h5>  No Room Rent Cap </h5>
<p>Covered for rooms (except suites or above) for SI ₹ 5 lakhs & above </p>
<h5>  Health check-up </h5>
<p>Pick tests based on your needs and avail cashless health check-ups </p>
<h5>No Claim Bonus </h5>
<p>Get 20% more sum insured at renewal for each claim free year; max up to 100% </p>


<hr />

<hr />
<div class="col">
<a asp-action="Index" class="btn btn-success w-100"> Back to Policy Details</a>
</div>

HealthInsurenceSystem/Views/Policies/Index.cshtml
    @model IEnumerable<HealthInsurenceSystem.Models.Policy>

<head>

    <title>
        Policy Recommendation Page
    </title>
</head>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Policies List</h2>
        </div>
        
    </div>

    <br/> <br/>

    @if (Model.Count() > 0)
    {

        <table class="table table-bordered table-striped" style="width:100%">

            <thead>
                <tr>
                    <th>
                        Policy Type
                    </th>
                    <th>
                        Minimum Age
                    </th>
                    <th>
                        Maximum Age
                    </th>
                    <th>
                        Month Premium
                    </th>
                    <th>
                        Duration
                    </th>
                    <th> More Details</th>
                    <th>Inquiry</th>
                </tr>
            </thead>
            <tbody>
                @foreach(var obj in Model)
                {
                <tr>
                    <td width="15%">@obj.Ptype</td>
                    <td width="10%">@obj.MinAge</td>
                    <td width="10%">@obj.MaxAge</td>
                    <td width="10%">@obj.MonthPremium</td>
                    <td width="10%">@obj.Duration</td>
                    <td width="15%"><a asp-controller="Policies"  asp-action=@obj.Ptype.Replace(" ", "") class="btn btn-primary">Know More </a></td>
                    <td width="20%" class="text-center">
                        <a asp-controller="Policies"   asp-action="addtocart" class="btn btn-success"> Interested </a>
                        

</td>
                </tr>


                }
            </tbody>
        </table>
    }
    else
    {
        <p> No new Policy exists</p>
    }


</div>

HealthInsurenceSystem/Views/Policies/Interest.cshtml
@model IEnumerable<HealthInsurenceSystem.Models.Paymentlog>

<head>

    <title>
        Policy Information
    </title>
</head>
<div class="jumbotron text-center">
    <h1 class="display-3">Thank You!</h1>

    <p class="lead"><h3> We have recored your interest.</h3></p>
    <hr><br />
    <p>Our Agent Contact You soon</p><br />
   <p> Secure Your Future with Us. Give us chance to help you.</p>
    <p> Stay Safe.</p>
    <br />
    <p>
        Check our Policies.
    </p>
    <p class="lead">
        <a asp-controller="Home" asp-action="Index" class="btn btn-primary btn-block">Go to Home</a>
    </p>
</div>

HealthInsurenceSystem/Views/Policies/Platinum.cshtml
@{
    ViewData["Title"] = "knowmore";
}

<h1>More About Health Insurance Plans</h1>
<img src="https://www.what-a-blog.com/wp-content/uploads/2020/05/aa-Cover-0mfd5vvu77f1bvrtjhg0fc7t54-20200330160440.Medi_.jpeg" />
<img src="https://www.policybazaar.com/images/Health/what-is-health-insurance.png" />


<h3><u>Platinum Plan</u></h3>
<h5>Direct Claim Settlement </h5>
<p>No third party agents involved. Get your claims processed painlessly by our customer service team directly. </p>

<h5> All Day Care Treatments </h5>
<p>Your health insurance will cover host of day care procedures. </p>
<h5>  Pre & Post Hospitalisation </h5>
<p>We cover expenses 30 days before hospitalisation and 60 days post-discharge.</p>
<h5>  No Room Rent Cap </h5>
<p>Covered for rooms (except suites or above) for SI ₹ 5 lakhs & above </p>
<h5>  Health check-up </h5>
<p>Pick tests based on your needs and avail cashless health check-ups </p>
<h5>No Claim Bonus </h5>
<p>Get 20% more sum insured at renewal for each claim free year; max up to 100% </p>
<h5>Alternative treatment </h5>
<p>  Get cover for Ayurvedic, Unani, Siddha and Homeopathic treatments </p>

<hr />
<hr />
<div class="col">
<a asp-action="Index" class="btn btn-success w-100"> Back to Policy Details</a>
</div>

HealthInsurenceSystem/Views/Policies/Silver.cshtml
@{
    ViewData["Title"] = "knowmore";
}

<h1>More About Health Insurance Plans</h1>
<img src="https://www.what-a-blog.com/wp-content/uploads/2020/05/aa-Cover-0mfd5vvu77f1bvrtjhg0fc7t54-20200330160440.Medi_.jpeg" />
<img src="https://www.policybazaar.com/images/Health/what-is-health-insurance.png" />


<h3><u>Silver Plan</u></h3>

<h5> All Day Care Treatments </h5>
<p>Your health insurance will cover host of day care procedures. </p>

<h5>  Pre & Post Hospitalisation </h5>
<p>We cover expenses 30 days before hospitalisation and 60 days post-discharge.</p>



<hr />

<div class="col">
<a asp-action="Index" class="btn btn-success w-100"> Back to Policy Details</a>
</div>

HealthInsurenceSystem/Views/Policies/Standard.cshtml
@{
    ViewData["Title"] = "knowmore";
}

<h1>More About Health Insurance Plans</h1>
<img src="https://www.what-a-blog.com/wp-content/uploads/2020/05/aa-Cover-0mfd5vvu77f1bvrtjhg0fc7t54-20200330160440.Medi_.jpeg" />
<img src="https://www.policybazaar.com/images/Health/what-is-health-insurance.png" />
<h3><u>Standard Plan</u></h3>

<h5>  Pre & Post Hospitalisation </h5>
<p>We cover expenses 30 days before hospitalisation and 60 days post-discharge.</p>


<h5>No Claim Bonus </h5>
<p>Get 20% more sum insured at renewal for each claim free year; max up to 100% </p>


<hr />

<div class="col">
<a asp-action="Index" class="btn btn-success w-100"> Back to Policy Details</a>
</div>

HealthInsurenceSystem/Views/Policies/SuperPlatinum.cshtml
@{
    ViewData["Title"] = "knowmore";
}

<h1>More About Health Insurance Plans</h1>
<img src="https://www.what-a-blog.com/wp-content/uploads/2020/05/aa-Cover-0mfd5vvu77f1bvrtjhg0fc7t54-20200330160440.Medi_.jpeg" />
<img src="https://www.policybazaar.com/images/Health/what-is-health-insurance.png" />
<h3><u>Super Platinum Plan</u></h3>
<h5>Includes Covid Treatment and Vaccination </h5>
<p>If you stay in a hospital for more than 10 days at a stretch then we pay for other financial losses that might have happened due to your absence at home. It helps to take care of other expenses during your hospitalization. (Amount specified in the policy wording)</p>

<h5>Recovery benefit</h5>
<p>If you stay in a hospital for more than 10 days at a stretch then we pay for other financial losses that might have happened due to your absence at home. It helps to take care of other expenses during your hospitalization. (Amount specified in the policy wording) </p>


<h5>Direct Claim Settlement </h5>
<p>No third party agents involved. Get your claims processed painlessly by our customer service team directly. </p>

<h5> All Day Care Treatments </h5>
<p>Your health insurance will cover host of day care procedures. </p>
<h5>  Pre & Post Hospitalisation </h5>
<p>We cover expenses 30 days before hospitalisation and 60 days post-discharge.</p>
<h5>  No Room Rent Cap </h5>
<p>Covered for rooms (except suites or above) for SI ₹ 5 lakhs & above </p>
<h5>  Health check-up </h5>
<p>Pick tests based on your needs and avail cashless health check-ups </p>
<h5>No Claim Bonus </h5>
<p>Get 20% more sum insured at renewal for each claim free year; max up to 100% </p>
<h5>Alternative treatment </h5>
<p>  Get cover for Ayurvedic, Unani, Siddha and Homeopathic treatments </p>
<hr />
<hr />
<div class="col">
    <a asp-action="Index" class="btn btn-success w-100"> Back to Policy Details</a>
</div>

HealthInsurenceSystem/Views/Policies/addtocart.cshtml
@model HealthInsurenceSystem.Models.Interested

<h1>Policy Inquiry</h1>
<hr />
<hr />

<h2>Fill this details</h2>


<form method="post" asp-action="addtocart">

    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-info pl-3">Information</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Cemail">Email Address</label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Cemail" class="form-control" />
                        <span asp-validation-for="Cemail" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Amount"> Your Budget </label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Ptype"> Policy Name </label>
                    </div>
                    <div class="col-8">
                        <div class="col-8">
                            @Html.RadioButtonFor(m => m.Ptype, "Standard") Standard<br />
                            @Html.RadioButtonFor(m => m.Ptype, "Gold")Gold<br />
                            @Html.RadioButtonFor(m => m.Ptype, "Diamond")Diamond<br />
                            @Html.RadioButtonFor(m => m.Ptype, "Platinum")Platinum<br />
                            @Html.RadioButtonFor(m => m.Ptype, "Platinum")Super Platinum<br />
                        </div>
                    </div>

                </div>
                
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Submit" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>

    </div>

</form>

HealthInsurenceSystem/Views/Policies/deletefromcart.cshtml
@model HealthInsurenceSystem.Models.Policy
@{
    ViewData["Title"] = "deletefromcart";
}

<h1>Remove Policy from Cart</h1>
<hr />
<hr />
<h2> Policy has been selected for removal</h2>



<form method="post">
    <input asp-for="Ptype" hidden />
    <div class="border p-3">

        <div class="form-group row">
            <h2 class="text-info pl-3">Click on Remove Policy to remove from Cart</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Ptype"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Ptype" class="form-control" />
                        <span asp-validation-for="Ptype" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="MonthPremium"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="MonthPremium" class="form-control" />
                        <span asp-validation-for="MonthPremium" class="text-danger"></span>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">

                        <div class="col">
                           <a asp-action="Index" class="btn btn-info w-100"> Remove Policy </a>
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                @* Keep this empty *@
            </div>
        </div>
    </div>

</form>

HealthInsurenceSystem/Views/Policies/knowmore.cshtml
@{
    ViewData["Title"] = "knowmore";
}

<h1>More About Health Insurance Plans</h1>
<img src="https://www.what-a-blog.com/wp-content/uploads/2020/05/aa-Cover-0mfd5vvu77f1bvrtjhg0fc7t54-20200330160440.Medi_.jpeg" />
<img src="https://www.policybazaar.com/images/Health/what-is-health-insurance.png" />
<h3><u>Standard Plan</u></h3>

<h5>  Pre & Post Hospitalisation </h5>
<p>We cover expenses 30 days before hospitalisation and 60 days post-discharge.</p>


<h5>No Claim Bonus </h5>
<p>Get 20% more sum insured at renewal for each claim free year; max up to 100% </p>


<hr />

<h3><u>Silver Plan</u></h3>

<h5> All Day Care Treatments </h5>
<p>Your health insurance will cover host of day care procedures. </p>

<h5>  Pre & Post Hospitalisation </h5>
<p>We cover expenses 30 days before hospitalisation and 60 days post-discharge.</p>



<hr />

<h3><u>Gold Plan</u></h3>
<h5>Direct Claim Settlement </h5>
<p>No third party agents involved. Get your claims processed painlessly by our customer service team directly. </p>

<h5> All Day Care Treatments </h5>
<p>Your health insurance will cover host of day care procedures. </p>
<h5>  Pre & Post Hospitalisation </h5>
<p>We cover expenses 30 days before hospitalisation and 60 days post-discharge.</p>
<h5>  No Room Rent Cap </h5>
<p>Covered for rooms (except suites or above) for SI ₹ 5 lakhs & above </p>
<h5>  Health check-up </h5>
<p>Pick tests based on your needs and avail cashless health check-ups </p>
<h5>No Claim Bonus </h5>
<p>Get 20% more sum insured at renewal for each claim free year; max up to 100% </p>


<hr />

<h3><u>Platinum Plan</u></h3>
<h5>Direct Claim Settlement </h5>
<p>No third party agents involved. Get your claims processed painlessly by our customer service team directly. </p>

<h5> All Day Care Treatments </h5>
<p>Your health insurance will cover host of day care procedures. </p>
<h5>  Pre & Post Hospitalisation </h5>
<p>We cover expenses 30 days before hospitalisation and 60 days post-discharge.</p>
<h5>  No Room Rent Cap </h5>
<p>Covered for rooms (except suites or above) for SI ₹ 5 lakhs & above </p>
<h5>  Health check-up </h5>
<p>Pick tests based on your needs and avail cashless health check-ups </p>
<h5>No Claim Bonus </h5>
<p>Get 20% more sum insured at renewal for each claim free year; max up to 100% </p>
<h5>Alternative treatment </h5>
<p>  Get cover for Ayurvedic, Unani, Siddha and Homeopathic treatments </p>

<hr />
<hr />
<div class="col">
<a asp-action="Index" class="btn btn-success w-100"> Back to Policy Details</a>
</div>

HealthInsurenceSystem/Views/Policies/payonline.cshtml
@{
    ViewData["Title"] = "payonline";
}

<h1>Pay Online</h1>

<p>Policy has been added to your profile. You will receive the payment link once Agent approves your documents</p>

<hr />
<hr />

<div class="col">
    <a asp-action="Index" class="btn btn-info w-100"> Click to Proceed with Payment. Approval Pending!!!</a>
</div>
<hr />
<hr />
<div class="col">
    <a asp-action="Index" class="btn btn-success w-100"> Back to Policy Details</a>
</div>