HealthInsurenceSystem/Controllers/AdminController.cs
using HealthInsurenceSystem.Data;
using HealthInsurenceSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HealthInsurenceSystem.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AdminController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult AddAgent()
        {
            return View();
        }
        public IActionResult AddedAgent()
        {
            return View();
        }
        public IActionResult AddedPolicy()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddAgent(Person obj)
        {

            if (ModelState.IsValid)
            {
                _db.Person.Add(obj);
                _db.SaveChanges();
                Person p = _db.Person.Where(a => a.Email == obj.Email).First();
                TempData["cnm"] = p.Cnumber;
                TempData["dob"] = p.Dob;
                TempData["em"] = p.Email;
                TempData["nam"] = p.Name;
                TempData["pass"] = p.Password;
                return RedirectToAction("AddedAgent");
            }
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(Policy obj)
        {

            if (ModelState.IsValid)
            {
                _db.Policy.Add(obj);
                _db.SaveChanges();
                TempData["Ptype"]=obj.Ptype;
                TempData["pre"]=obj.MonthPremium;
                TempData["max"]=obj.MaxAge;
                TempData["min"] = obj.MinAge;
                TempData["dur"] = obj.Duration;
                return RedirectToAction("AddedPolicy");
            }
            return View(obj);
        }
    }
}

HealthInsurenceSystem/Controllers/AgentController.cs
using HealthInsurenceSystem.Data;
using HealthInsurenceSystem.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HealthInsurenceSystem.Controllers
{
    public class AgentController : Controller
    {
        private readonly ApplicationDbContext _db;

        public AgentController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Purchased()
        {
            return View();
        }
        public IActionResult Sold()
        {
            string agent = HttpContext.Session.GetString("emailID");
            IEnumerable<Customer>  c =_db.Customer.Where(a=>a.Aemail==agent);
            return View(c);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(Customer obj)
        {
            Policy p = _db.Policy.Find(obj.Ptype);
            obj.Duration = (int)p.Duration;
            obj.Amount = (int)p.MonthPremium;
            obj.Aemail= HttpContext.Session.GetString("emailID");
            DateTime now = DateTime.Today;
            obj.Purchaseddate = now;
            _db.Customer.Add(obj);
            _db.SaveChanges();
            return View("Purchased", obj);
        }
    }
}

HealthInsurenceSystem/Controllers/PersonController.cs
using HealthInsurenceSystem.Data;
using HealthInsurenceSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;
using System.Text.RegularExpressions;

namespace HealthInsurenceSystem.Controllers
{
    public class PersonController : Controller
    {

        private readonly ApplicationDbContext _db;

        public PersonController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult login()
        {
            return View();
        }
        public IActionResult ok()
        {
            return View();
        }
        public IActionResult Notok()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult login(Person obj)
        {
            IEnumerable<Person> x1 = _db.Person.Where(a=>a.Email==obj.Email && a.Password==obj.Password);
            
            if (ModelState.IsValid) 
            {
                if (x1.Count()>0)
                {
                    int x = x1.First().Email.IndexOf("his");
                    int y = x1.First().Email.IndexOf("admin");
                    if (x-y==6)
                    {
                        HttpContext.Session.SetInt32("loggedIn", 3);
                        HttpContext.Session.SetString("emailID", x1.First().Email);
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        if (x1.First().Email.IndexOf("his") > 0)
                        {
                            HttpContext.Session.SetInt32("loggedIn", 2);
                            HttpContext.Session.SetString("emailID", x1.First().Email);
                            return RedirectToAction("Index", "Home");
                        }
                        else
                        {
                            HttpContext.Session.SetInt32("loggedIn", 1);
                            HttpContext.Session.SetString("emailID", x1.First().Email);
                            return RedirectToAction("Index", "Home");
                        }
                    }
                }
                else
                {
                    return RedirectToAction("Notok");
                }
            }
            return RedirectToAction("Notok");
        }
        public IActionResult signup()
        {
            return View();
        }
        //POST - CREATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult signup(Person obj)
        {
            if (ModelState.IsValid)
            {
                _db.Person.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("login");
            }
            return View(obj);
        }
    }
}

HealthInsurenceSystem/Controllers/PolicyController.cs
using HealthInsurenceSystem.Data;
using HealthInsurenceSystem.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HealthInsurenceSystem.Controllers
{
    public class PolicyController : Controller
    {
        private readonly ApplicationDbContext _db;

        public PolicyController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            String email = HttpContext.Session.GetString("emailID"); 
            IEnumerable<Customer> x1 = _db.Customer.Where(a => a.Cemail == email);
            
            return View(x1);
        }
    }
}

HealthInsurenceSystem/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HealthInsurenceSystem</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SMU Health Insurance</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Policies" asp-action="Index">Policy Details</a>
                        </li>
                        @if (Context.Session.GetInt32("loggedIn") == 1)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Policy" asp-action="Index">Purchased Policy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">log out</a>
                            </li>
                        }
                        else
                        {

                            @if (Context.Session.GetInt32("loggedIn") == 2)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Agent" asp-action="Index">New Policy</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Agent" asp-action="Sold">Sold Policy</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">log out</a>
                                </li>
                            }
                            else
                            {


                                @if (Context.Session.GetInt32("loggedIn") == 3)
                                {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Add Policy</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AddAgent">Add Agent</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">log out</a>
                                </li>
                                }

                                else
                                {
                                @if (Context.Session.GetInt32("loggedIn") != 1)
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Payment" asp-action="Index">Quick Payment</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact Us</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="login">Log In</a>
                                    </li>
                                }
                                }
                                }
                            }


                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HealthInsurenceSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HealthInsurenceSystem/Views/Shared/ok.cshtml
@model HealthInsurenceSystem.Models.Person

<div>
    Thank you!
</div>